version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.8
    volumes:
      - data-mongo-1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - mongors-network
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    command: "/usr/bin/mongod --bind_ip_all --replSet dbrs"

networks:
  mongors-network:
    driver: bridge

volumes:
  data-mongo-1:
    external: true